/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.awt.*;
import java.awt.event.ActionEvent;
import javax.swing.*;

/**
 *
 * @author pierre
 */
public class GestionVue extends GestionVueAbstraite{
    /**
     * Creates new form GestionVueProg
     */
    public GestionVue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")                       
    private void initComponents() {

        mainPanel = new JPanel();
        nomLabel = new JLabel();
        adresseLabel = new JLabel();
        responsableLabel = new JLabel();
        hobbyLabel = new JLabel();
        prenomLabel = new JLabel();
        pseudoLabel = new JLabel();
        naissLabel = new JLabel();
        embLabel = new JLabel();
        nomTextField = new JTextField();
        adresseTextField = new JTextField();
        responsableTextField = new JTextField();
        hobbyTextField = new JTextField();
        prenomTextField = new JTextField();
        pseudoTextField = new JTextField();
        jourNaissTextField = new JTextField();
        jourEmbTextField = new JTextField();
        anneeNaissTextField = new JTextField();
        anneeEmbTextField = new JTextField();
        jComboBox1 = new JComboBox<>();
        jComboBox2 = new JComboBox<>();
        rechercherButton = new JButton();
        reinitButton = new JButton();
        validerButton = new JButton();
        annulerButton = new JButton();
        matriculePanel = new JPanel();
        matriculeLabel = new JLabel();
        matriculeTextField = new JTextField();
        mainMenu = new JMenuBar();
        progMenu = new JMenu();
        afficherMenuItem = new JMenuItem();
        modifierMenuItem = new JMenuItem();
        supprimerMenuItem = new JMenuItem();
        ajouterMenuItem = new JMenuItem();
        actionMenu = new JMenu();
        quitterMenuItem = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("GesProg");

        nomLabel.setText("Nom");

        adresseLabel.setText("Adresse");

        responsableLabel.setText("Responsable");

        hobbyLabel.setText("Hobby");

        prenomLabel.setText("Prénom");

        pseudoLabel.setText("Pseudo");

        naissLabel.setText("Date de naissance");

        embLabel.setText("Date d'embauche");

        jourNaissTextField.setToolTipText("jour");

        jourEmbTextField.setToolTipText("jour");

        anneeNaissTextField.setToolTipText("année");

        anneeEmbTextField.setToolTipText("année");

        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rechercherButton.setText("Rechercher");
        rechercherButton.addActionListener((java.awt.event.ActionEvent evt) -> {
            rechercherButtonActionPerformed(evt);
        });

        reinitButton.setText("Réinitialiser");
        reinitButton.addActionListener((java.awt.event.ActionEvent evt) -> {
            reinitButtonActionPerformed(evt);
        });

        validerButton.setText("Valider");
        validerButton.addActionListener((java.awt.event.ActionEvent evt) -> {
            validerButtonActionPerformed(evt);
        });

        annulerButton.setText("Annuler");
        annulerButton.addActionListener((java.awt.event.ActionEvent evt) -> {
            annulerButtonActionPerformed(evt);
        });

        GroupLayout mainPanelLayout = new GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(nomLabel)
                            .addComponent(adresseLabel)
                            .addComponent(responsableLabel)
                            .addComponent(hobbyLabel))
                        .addGap(24, 24, 24)
                        .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomTextField)
                            .addComponent(adresseTextField)
                            .addComponent(responsableTextField)
                            .addComponent(hobbyTextField, GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(prenomLabel)
                            .addComponent(pseudoLabel)
                            .addComponent(naissLabel)
                            .addComponent(embLabel))
                        .addGap(21, 21, 21)
                        .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prenomTextField)
                                    .addComponent(pseudoTextField, GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(jourNaissTextField, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jourEmbTextField, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(anneeNaissTextField, GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(anneeEmbTextField))
                        .addGap(37, 37, 37))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(rechercherButton)
                        .addGap(18, 18, 18)
                        .addComponent(reinitButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(validerButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(annulerButton)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(nomLabel)
                    .addComponent(prenomLabel)
                    .addComponent(nomTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenomTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(adresseLabel)
                    .addComponent(pseudoLabel)
                    .addComponent(adresseTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(pseudoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(responsableLabel)
                    .addComponent(naissLabel)
                    .addComponent(responsableTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jourNaissTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(anneeNaissTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(hobbyLabel)
                    .addComponent(embLabel)
                    .addComponent(hobbyTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jourEmbTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(anneeEmbTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(rechercherButton)
                    .addComponent(reinitButton)
                    .addComponent(validerButton)
                    .addComponent(annulerButton))
                .addContainerGap())
        );

        matriculePanel.setBackground(new Color(0, 0, 0));

        matriculeLabel.setForeground(new Color(255, 255, 255));
        matriculeLabel.setHorizontalAlignment(SwingConstants.CENTER);
        matriculeLabel.setText("Matricule");
        matriculeLabel.setAlignmentY(0.0F);

        matriculeTextField.setText("0");

        GroupLayout matriculePanelLayout = new GroupLayout(matriculePanel);
        matriculePanel.setLayout(matriculePanelLayout);
        matriculePanelLayout.setHorizontalGroup(
            matriculePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(matriculePanelLayout.createSequentialGroup()
                .addComponent(matriculeLabel, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matriculeTextField, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 462, Short.MAX_VALUE))
        );
        matriculePanelLayout.setVerticalGroup(
            matriculePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, matriculePanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(matriculeLabel, GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addComponent(matriculeTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        progMenu.setText("Programmeur");

        afficherMenuItem.setText("Afficher");
        afficherMenuItem.addActionListener((ActionEvent evt) -> {
            afficherMenuItemActionPerformed(evt);
        });
        progMenu.add(afficherMenuItem);

        modifierMenuItem.setText("Modifier");
        modifierMenuItem.addActionListener((ActionEvent evt) -> {
            modifierMenuItemActionPerformed(evt);
        });
        progMenu.add(modifierMenuItem);

        supprimerMenuItem.setText("Supprimer");
        supprimerMenuItem.addActionListener((ActionEvent evt) -> {
            supprimerMenuItemActionPerformed(evt);
        });
        progMenu.add(supprimerMenuItem);

        ajouterMenuItem.setText("Ajouter");
        ajouterMenuItem.addActionListener((ActionEvent evt) -> {
            ajouterMenuItemActionPerformed(evt);
        });
        progMenu.add(ajouterMenuItem);

        mainMenu.add(progMenu);

        actionMenu.setText("Action");

        quitterMenuItem.setText("Quitter");
        quitterMenuItem.addActionListener((ActionEvent evt) -> {
            quitterMenuItemActionPerformed(evt);
        });
        actionMenu.add(quitterMenuItem);

        mainMenu.add(actionMenu);

        setJMenuBar(mainMenu);

        layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            //.addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(matriculePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(matriculePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
                //.addComponent(mainPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }                       

    private void quitterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                
        int result = JOptionPane.showConfirmDialog(this,"Vérification" , "Voulez-vous vraiment quitter?",JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.OK_OPTION) {
            //ferme
            this.dispose();
        }
    }                                               

    private void afficherMenuItemActionPerformed(ActionEvent evt) {                                                 
        
    }                                                

    private void modifierMenuItemActionPerformed(ActionEvent evt) {                                                 
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }                                                

    private void supprimerMenuItemActionPerformed(ActionEvent evt) {                                                  
        
    }                                                 

    private void ajouterMenuItemActionPerformed(ActionEvent evt) {                                                
        
    }                                               

    private void rechercherButtonActionPerformed(ActionEvent evt) {                                                 
        
    }                                                

    private void reinitButtonActionPerformed(ActionEvent evt) {                                             
        
    }                                            

    private void validerButtonActionPerformed(ActionEvent evt) {                                              
        
    }                                             

    private void annulerButtonActionPerformed(ActionEvent evt) {                                              
        
    }                                             

    /**
     * @param args the command line arguments
     */
    
    //to delete
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("WindowsLookAndFeel".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionVueProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionVueProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionVueProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionVueProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionVueProg().setVisible(true);
            }
        });
    }

    // Variables declaration
    private GroupLayout layout;
    private JMenu actionMenu;
    private JLabel adresseLabel;
    private JTextField adresseTextField;
    private JMenuItem afficherMenuItem;
    private JMenuItem ajouterMenuItem;
    private JTextField anneeEmbTextField;
    private JTextField anneeNaissTextField;
    private JButton annulerButton;
    private JLabel embLabel;
    private JLabel hobbyLabel;
    private JTextField hobbyTextField;
    private JComboBox<String> jComboBox1;
    private JComboBox<String> jComboBox2;
    private JTextField jourEmbTextField;
    private JTextField jourNaissTextField;
    private JMenuBar mainMenu;
    private JPanel mainPanel;
    private JLabel matriculeLabel;
    private JPanel matriculePanel;
    private JTextField matriculeTextField;
    private JMenuItem modifierMenuItem;
    private JLabel naissLabel;
    private JLabel nomLabel;
    private JTextField nomTextField;
    private JLabel prenomLabel;
    private JTextField prenomTextField;
    private JMenu progMenu;
    private JLabel pseudoLabel;
    private JTextField pseudoTextField;
    private JMenuItem quitterMenuItem;
    private JButton rechercherButton;
    private JButton reinitButton;
    private JLabel responsableLabel;
    private JTextField responsableTextField;
    private JMenuItem supprimerMenuItem;
    private JButton validerButton;
    // End of variables declaration   
}
